name: Build and Release

on:
  push:
    branches:
      - main  # Запускать workflow на push в ветку main
    tags:
      - 'v*'  # Также запускать на тегах вида v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Build package
        run: |
          poetry build

      - name: Run Semantic Release
        uses: matteo4diani/poetry-semantic-release@v0
        with:
          versioning: "semver"  # Использовать Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub автоматически предоставляет этот токен
          
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
